const stays = [
  {eyebrow:"Sleep under canvas",title:"The Yurt",text:"A wood-fired hideaway for four, with its own shepherd’s-hut kitchen and bathroom beside the stream.",cta:"Check availability on Airbnb",href:"https://www.airbnb.co.uk/rooms/38643867",image:"/images/04-IMG_9267.webp",alt:"Cwm Sticky Dingle yurt and private shepherd's hut",note:"4 guests · private kitchen · private bathroom"},
  {eyebrow:"A vintage escape",title:"Willowbrook",text:"A lovingly converted 1970s bus, hidden among trees with spring water, solar power and the valley at your door.",cta:"Check availability on Canopy & Stars",href:"https://www.canopyandstars.co.uk/britain/wales/monmouthshire/tyr-trawst/willowbrook",image:"/images/02-IMG_9455.webp",alt:"Willowbrook vintage bus tucked among the trees",note:"2 guests · private kitchen · private bathroom"},
];
const events=["Intimate weddings","Performances","Microfestivals","School & charity trips","Retreats","Private gatherings"];
const extras=[["01","Stay","Yurt · Willowbrook · event yurt · camping"],["02","Feast","Catering · bar · firepit · field kitchen · BBQ"],["03","Stage","Sound · lighting · marquees · performance space"]];
const adventures=[["01","The Blorenge","Mountain walk · 4–7 miles","Heather, big skies and views across the Vale of Usk."],["02","Keeper’s Pond","Wild swim · 10 min drive","An upland pool shaped by the ironworkers of Blaenavon."],["03","Gilwern Hill","Climbing · on the doorstep","Limestone crags with more than a hundred established routes."],["04","Mon & Brec Canal","Walk or cycle · from Govilon","A gentle towpath journey through wooded hills and villages."]];
export default function Home(){return <main>
<header className="site-header"><a className="wordmark" href="#top"><span className="mark">CSD</span><span>Cwm Sticky Dingle</span></a><nav><a href="#stay">Stay</a><a href="#gather">Gather</a><a href="/guest-guide">Guest guide</a><a href="#story">Our story</a></nav><a className="header-cta" href="#enquire">Plan a gathering <span>↗</span></a></header>
<section className="hero" id="top"><img className="hero-image" src="/images/01-IMG_9466.webp" alt="Willowbrook among tall trees in the Cwm Sticky Dingle valley"/><div className="hero-shade"/><div className="contours"/><div className="hero-copy"><p className="kicker light">Govilon · Bannau Brycheiniog · Wales</p><h1>Stay wild.<br/>Gather differently.</h1><p className="hero-intro">Two extraordinary off-grid stays and a woodland roundhouse, hidden in a secret Welsh valley.</p><div className="hero-actions"><a className="button button-light" href="#stay">Find your stay</a><a className="text-link" href="#gather">Host something special <span>↗</span></a></div></div><div className="hero-location"><span className="pulse"/><span>Between the Blorenge<br/>&amp; Gilwern Hill</span></div><a className="scroll" href="#intro"><span>Discover</span><span>↓</span></a></section>
<section className="intro-section" id="intro"><p className="vertical-label">A hidden valley in South Wales</p><div className="intro-copy"><p className="kicker">Come off the road</p><h2>Follow the stream.<br/>Lose the signal.<br/><em>Find the place.</em></h2></div><div className="intro-note"><p>Far from traffic and streetlights, the Dingle is a place of running water, deep woods and open fires—only 3.5 miles from Abergavenny, but a world away.</p><a className="text-link" href="#story">Meet the valley <span>→</span></a></div><div className="sun-seal"><span>51.82° N</span><strong>☼</strong><span>3.07° W</span></div></section>
<section className="stay-section" id="stay"><div className="section-heading"><div><p className="kicker">Stay awhile</p><h2>Two stays.<br/>One wild valley.</h2></div><p>Characterful, self-contained and completely private. Each has its own kitchen and bathroom, with the woods, streams and firepit shared only with the birds.</p></div><div className="stay-grid">{stays.map(s=><article className="stay-card" key={s.title}><img src={s.image} alt={s.alt}/><div className="stay-gradient"/><div className="stay-copy"><p className="kicker light">{s.eyebrow}</p><h3>{s.title}</h3><p>{s.text}</p><small>{s.note}</small><a href={s.href} target="_blank" rel="noreferrer">{s.cta}<span>↗</span></a></div></article>)}</div></section>
<section className="gather-section" id="gather"><div className="roundhouse-image"><img src="/images/08-IMG_9270.webp" alt="Hand-built woodland roundhouse at Cwm Sticky Dingle"/><div className="roundhouse-label"><span>New</span>The Roundhouse</div></div><div className="gather-copy"><p className="kicker light">Gather in the woods</p><h2>A space with<br/>a story to tell.</h2><p className="large-copy">A timber roundhouse and open camping ground for celebrations, performances, retreats and ideas that need room to breathe.</p><div className="event-tags">{events.map(e=><span key={e}>{e}</span>)}</div><a className="button button-rust" href="#enquire">Explore gatherings</a></div></section>
<section className="build-event"><div className="event-title"><p className="kicker">Build your gathering</p><h2>Bring the idea.<br/><em>We’ll shape the rest.</em></h2></div><div className="extras-list">{extras.map(([n,t,x])=><div className="extra" key={n}><span>{n}</span><h3>{t}</h3><p>{x}</p><b>＋</b></div>)}</div></section>
<section className="break-image"><img src="/images/10-IMG_9260.webp" alt="Wooden swing beneath an old tree at Cwm Sticky Dingle"/><div><p className="kicker light">Room to breathe</p><p>Camp under old trees.<br/>Cook over fire.<br/>Stay up late.</p></div></section>
<section className="explore-section" id="explore"><div className="explore-top"><div><p className="kicker light">Step beyond the gate</p><h2>The wild is<br/>closer than you think.</h2></div><p>Walk, swim, climb, fly or simply follow the canal to lunch. We’ll point you towards the best routes, seasonal conditions and people who know the hills.</p></div><div className="map-area"><div className="map-pin pin-1"><i/>Cwm Sticky Dingle<small>You are here</small></div><div className="map-pin pin-2"><i/>The Blorenge<small>561 m</small></div><div className="map-pin pin-3"><i/>Keeper’s Pond<small>Wild swimming</small></div><div className="map-pin pin-4"><i/>Govilon<small>Canal &amp; village</small></div><div className="compass"><span>N</span><b>↑</b></div></div><div className="adventure-list">{adventures.map(([n,t,m,d])=><article key={n}><span>{n}</span><div><h3>{t}</h3><small>{m}</small></div><p>{d}</p><b>↗</b></article>)}</div><a className="guide-home-cta" href="/guest-guide">Open the complete guest guide <span>↗</span></a></section>
<section className="story-section" id="story"><div className="story-photo"><img src="/images/03-IMG_9305.webp" alt="Woodland path through Cwm Sticky Dingle"/><div className="story-ring"><span>Wales</span><strong>✦</strong><span>Cordell Country</span></div></div><div className="story-copy"><p className="kicker">Lore of the land</p><h2>Iron, water<br/>and old stories.</h2><p className="large-copy">These hills carry the marks of ironworkers, canal builders, drovers and dreamers. Alexander Cordell set his stories in this landscape; today the old tracks still run above the valley.</p><p>We’re collecting the history, names and family memories of the Dingle to share without sanding away the rough edges.</p><a className="text-link" href="#enquire">Read the valley story <span>→</span></a></div></section>
<section className="enquire-section" id="enquire"><div><p className="kicker light">Your gathering starts here</p><h2>What could happen<br/>in the Dingle?</h2></div><div className="enquire-copy"><p>Tell us what you’re imagining—dates, guest numbers, sleeping plans and the extras you may need. We’ll help shape what is possible.</p><a className="button button-light" href="mailto:hello@cwmstickydingle.co.uk?subject=Gathering enquiry">Start an enquiry <span>↗</span></a></div></section>
<footer><div className="footer-brand"><span className="mark">CSD</span><h2>Cwm Sticky Dingle</h2><p>Stay wild. Gather differently.</p></div><div className="footer-links"><div><span>Discover</span><a href="#stay">Stay</a><a href="#gather">Gather</a><a href="/guest-guide">Guest guide</a></div><div><span>Follow</span><a href="https://www.instagram.com/cwmstickydingle/">Instagram</a><a href="https://www.facebook.com/p/Cwm-Sticky-Dingle-Glamping-100091745062482/">Facebook</a></div><div><span>Find us</span><p>Govilon<br/>Abergavenny<br/>South Wales</p></div></div><div className="footer-bottom"><span>Homepage concept · August 2026</span><a href="#top">Back to top ↑</a></div></footer>
</main>}
